Repository pulp/pulp_deb, pull requests merged in 2020-09, with the labels that each got.

#167 Add per repository package uniqueness constraints
  CHANGES/6429.doc
  CHANGES/6429.feature
  docs/feature_overview.rst
  pulp_deb/app/models/content.py
  pulp_deb/app/models/repository.py
Labels: .feature

#204 Update travis pipeline using latest plugin template
  .travis/Containerfile.j2
  .travis/before_install.sh
  .travis/before_script.sh
  .travis/build_container.yaml
  .travis/install.sh
  .travis/redmine.py
  .travis/release.py
  .travis/release_requirements.txt
  .travis/settings.py.j2
  .travis/start_container.yaml
  .travis/update_redmine.sh
  .travis/validate_commit_message.py
  template_config.yml
Labels: [noissue]

#205 Add select plugin template bootstrap changes
  .bumpversion.cfg
  CHANGES/.TEMPLATE.rst
  MANIFEST.in
  flake8.cfg
Labels: [noissue]

#206 Release 2.6.0b1
  .bumpversion.cfg
  CHANGES.rst
  CHANGES/6051.misc
  CHANGES/6429.doc
  CHANGES/6429.feature
  CHANGES/6506.doc
  CHANGES/6882.misc
  CHANGES/6991.bugfix
  CHANGES/7148.doc
  CHANGES/7153.bugfix
  CHANGES/7190.bugfix
  CHANGES/7211.doc
  CHANGES/7236.bugfix
  CHANGES/7257.bugfix
  CHANGES/7295.bugfix
  CHANGES/7318.doc
  CHANGES/7344.misc
  CHANGES/7355.doc
  pulp_deb/__init__.py
  requirements.txt
  setup.py
Labels: [noissue]

#210 Deprecation issues
  .travis/validate_commit_message.py
  pyproject.toml
Labels: [noissue]

#209 Prepare master for GA status
  .bumpversion.cfg
  .travis.yml
  .travis/release.py
  CHANGES/6999.misc
  pulp_deb/__init__.py
  setup.py
  template_config.yml
Labels: .misc

#211 Remove remaining beta tags
  .bumpversion.cfg
Labels: [noissue]

#207 Add plugin maintenance doc
  .travis/release_requirements.txt
  README.md
  docs/external_references.rst
  docs/index.rst
  docs/plugin_maintenance.rst
Labels: [noissue]
