Repository pulp/pulp_deb, pull requests merged in 2021-04, with the labels that each got.

#260 Replace workingdir with Python stdlib
  pulp_deb/app/tasks/publishing.py
Labels: [noissue]

#261 Allow remotes to be associated with repositories
  CHANGES/8520.feature
  pulp_deb/app/models/repository.py
  pulp_deb/app/viewsets/repository.py
Labels: .feature

#262 Fix translation file synchronization
  CHANGES/8410.bugfix
  pulp_deb/app/tasks/synchronizing.py
Labels: .bugfix

#269 Update changelog
  CHANGES.rst
Labels: [noissue]

#272 Update 2.9 release branch CI
  .ci/ansible/Containerfile.j2
  .ci/ansible/settings.py.j2
  .ci/ansible/start_container.yaml
  .ci/scripts/check_gettext.sh
  .ci/scripts/docs-builder.py
  .ci/scripts/publish_client_gem.sh
  .ci/scripts/publish_client_pypi.sh
  .ci/scripts/publish_plugin_pypi.sh
  .ci/scripts/release.py
  .ci/scripts/validate_commit_message.py
  .github/workflows/ci.yml
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  .github/workflows/scripts/before_install.sh
  .github/workflows/scripts/check_commit.sh
  .github/workflows/scripts/install.sh
  .github/workflows/scripts/script.sh
  .github/workflows/scripts/utils.sh
  docs/Makefile
  docs/_static/.this_makes_it_so_git_keeps_the__static_folder
  docs/_static/api.json
  template_config.yml
Labels: [noissue]
