Repository pulp/pulp_deb, pull requests merged in 2022-07, with the labels that each got.

#573 Sanitize package path before downloading
  CHANGES/571.bugfix
  pulp_deb/app/tasks/synchronizing.py
Labels: backport-2.17, backport-2.18, backport-2.16

#576 Fixing content serializer bugs
  CHANGES/575.bugfix
  pulp_deb/app/serializers/content_serializers.py
Labels: .bugfix, backport-2.17, backport-2.18, backport-2.16

#572 Convert download content test to pytest
  pulp_deb/tests/functional/api/test_download_content.py
Labels: [noissue]
