Repository pulp/pulp_deb, pull requests merged in 2023-05, with the labels that each got.

#744 Add the ability to define a structured package upload using the API
  CHANGES/743.feature
  pulp_deb/app/constants.py
  pulp_deb/app/serializers/content_serializers.py
  pulp_deb/tests/functional/api/test_crud_packages.py
  pulp_deb/tests/functional/api/test_download_policies.py
Labels: .feature

#759 Add removal warning about changed upload API behaviour
  CHANGES/592.removal
Labels: [noissue], .removal

#766 Fix infinite loading in the docs search bar
  CHANGES/765.doc
  doc_requirements.txt
  docs/conf.py
Labels: backport-2.18, backport-2.19, backport-2.20

#734 Update sync tests to use pytest
  pulp_deb/tests/functional/api/test_sync.py
  pulp_deb/tests/functional/api/test_sync_optimize.py
  pulp_deb/tests/functional/conftest.py
  pulp_deb/tests/functional/constants.py
  pulp_deb/tests/functional/data/debian/dists/ragnarok/asgard/debian-installer/binary-armeb/Packages
  pulp_deb/tests/functional/data/debian/dists/ragnarok/asgard/debian-installer/binary-armeb/Packages.gz
  pulp_deb/tests/functional/data/debian/dists/ragnarok/asgard/debian-installer/binary-ppc64/Packages
  pulp_deb/tests/functional/data/debian/dists/ragnarok/asgard/debian-installer/binary-ppc64/Packages.gz
Labels: [noissue], Tests

#771 Prep for pulpcore/3.25 compatibility.
  .github/workflows/scripts/script.sh
  CHANGES/770.feature
  pulp_deb/app/migrations/0022_alter_aptdistribution_distribution_ptr_and_more.py
  requirements.txt
  template_config.yml
Labels: .feature

#775 Test pulp-cli-deb
  .github/workflows/scripts/install.sh
  .github/workflows/scripts/script.sh
  template_config.yml
Labels: [noissue]
