Repository pulp/pulp_deb, pull requests merged in 2023-11, with the labels that each got.

#935 Simplify content fetching test fixtures
  pulp_deb/tests/functional/api/test_copy.py
  pulp_deb/tests/functional/api/test_download_policies.py
  pulp_deb/tests/functional/api/test_publish.py
  pulp_deb/tests/functional/api/test_pulpexport_pulpimport.py
  pulp_deb/tests/functional/api/test_sync.py
  pulp_deb/tests/functional/conftest.py
  pulp_deb/tests/functional/utils.py
Labels: Tests, backport-3.0

#944 Maintain the 3.1 branch
  template_config.yml
Labels: [noissue]

#922 Fix package repo uniqueness
  CHANGES/921.bugfix
  pulp_deb/app/models/content/content.py
  pulp_deb/app/models/content/structure_content.py
  pulp_deb/app/models/repository.py
  pulp_deb/app/tasks/exceptions.py
  pulp_deb/tests/functional/api/test_duplicate_packages.py
  pulp_deb/tests/functional/data/packages/duplicates/README.md
  pulp_deb/tests/functional/data/packages/duplicates/frigg_1.0_ppc64.deb
  pulp_deb/tests/functional/utils.py
Labels: .bugfix, Tests

#955 Stop supporting the 2.* branches
  template_config.yml
Labels: [noissue]

#920 Add pulp to pulp verification tests
  CHANGES/919.misc
  pulp_deb/tests/functional/api/test_pulp_to_pulp.py
  pulp_deb/tests/functional/conftest.py
  pulp_deb/tests/functional/constants.py
Labels: .misc, Tests, backport-3.0, backport-3.1

#945 Update the plugin maintenance docs
  docs/plugin_maintenance.rst
Labels: [noissue], backport-3.0, backport-3.1

#961 Have the CI manage the docs
  HISTORY.rst
  MANIFEST.in
  doc_requirements.txt
  docs/Makefile
  docs/_templates/restapi.html
  docs/changes.rst
  docs/conf.py
  docs/static/.gitkeep
  docs/template_gitref
  template_config.yml
Labels: [noissue]
